categories:
    path: /categories
    methods: [GET]
    controller: App\Controller\CategoryController::getAllCategories
category:
    path: /categories/{id}
    methods: [GET]
    controller: App\Controller\CategoryController::getCategory
category_delete:
    path: /categories/{id}
    methods: [DELETE]
    controller: App\Controller\CategoryController::deleteCategory
category_create:
    path: /categories
    methods: [POST]
    controller: App\Controller\CategoryController::createCategory
category_update:
    path: /categories/{id}
    methods: [PUT]
    controller: App\Controller\CategoryController::updateCategory


actors:
    path: /actors
    methods: [GET]
    controller: App\Controller\ActorController::getAllActors
actor:
    path: /actors/{id}
    methods: [GET]
    controller: App\Controller\ActorController::getActor
actor_delete:
    path: /actors/{id}
    methods: [DELETE]
    controller: App\Controller\ActorController::deleteActor
actor_create:
    path: /actors
    methods: [POST]
    controller: App\Controller\ActorController::createActor
actor_update:
    path: /actors/{id}
    methods: [PUT]
    controller: App\Controller\ActorController::updateActor


movies:
    path: /movies
    methods: [GET]
    controller: App\Controller\MovieController::getAllMovies
movie:
    path: /movies/{id}
    methods: [GET]
    controller: App\Controller\MovieController::getMovie
movie_delete:
    path: /movies/{id}
    methods: [DELETE]
    controller: App\Controller\MovieController::deleteMovie
movie_create:
    path: /movies
    methods: [POST]
    controller: App\Controller\MovieController::createMovie
movie_update:
    path: /movies/{id}
    methods: [PUT]
    controller: App\Controller\MovieController::updateMovie
